version: "2.4"

services:
  back:
    build:
      dockerfile: Dockerfile
      context: ../back
      # Only build development stage from Dockerfile
      target: development
    # Mount our host directory to the docker container
    # Mount api directory (./back) to (:) docker container (/back/src/app)
    # Reflect File changes from host to container
    volumes:
      - ../back:/back/src/app
      - /back/src/app/node_modules
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  front:
    build:
      dockerfile: Dockerfile
      context: ../front
      target: development
    command: npm run start
    volumes:
      - ../front:/front/src/app
      - /front/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - back

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

